-- 시험에 나옴!!!!!!

 ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- TEST0228

-- 사용자 생성
CREATE USER WORKBOOK IDENTIFIED BY WORKBOOK;

-- 권한 부여
GRANT RESOURCE, CONNECT TO WORKBOOK;

-- 테이블 스페이스 관련 설정
ALTER USER WORKBOOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;