 ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- TEST0228

-- 사용자 생성
CREATE USER TEST0228 IDENTIFIED BY TEST0228;

-- 권한 부여
GRANT RESOURCE, CONNECT TO TEST0228;

-- 테이블 스페이스 관련 설정
ALTER USER TEST0228 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;