/*
	SQL02_SELECT(Function)
*/

-- [1]
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- [2]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3
ORDER BY PROFESSOR_NAME;

-- [3]
SELECT PROFESSOR_NAME AS "교수이름",
TO_NUMBER(EXTRACT(YEAR FROM SYSDATE)) - TO_NUMBER((EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'YYYY'))) + 1900) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;

-- [4]
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) AS "이름"
FROM TB_PROFESSOR;

-- [5]
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE) - (EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'YYYY')) + 1900)) > 19;

-- [6]
SELECT TO_CHAR(TO_DATE('201225'), 'DY') FROM DUAL;

-- [7]
/*
	TO_DATE('99/10/11', 'YY/MM/DD')는 2099년 10월 11일을 의미
	TO_DATE('49/10/11', 'YY/MM/DD')는 2049년 10월 11일을 의미
	TO_DATE('99/10/11', 'RR/MM/DD')는 1999년 10월 11일을 의미
	TO_DATE('49/10/11', 'RR/MM/DD')는 2049년 10월 11일을 의미
*/
--SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11', 'YY/MM/DD')) FROM DUAL;
--SELECT EXTRACT(YEAR FROM TO_DATE('49/10/11', 'YY/MM/DD')) FROM DUAL;
--SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11', 'RR/MM/DD')) FROM DUAL;
--SELECT EXTRACT(YEAR FROM TO_DATE('49/10/11', 'RR/MM/DD')) FROM DUAL;

-- [8]
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

-- [9]
SELECT ROUND(AVG(POINT), 1) AS "학점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- [10]
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- [11]
SELECT COUNT(*)
FROM TB_STUDENT
GROUP BY COACH_PROFESSOR_NO
HAVING COACH_PROFESSOR_NO IS NULL;

-- [12]
--SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT), 1) AS "년도 별 평점"
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);

-- [13]
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 1)) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- [14]
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2
ORDER BY STUDENT_NAME;

-- [15]
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", SUBSTR(TERM_NO, 5, 2) AS "학기", ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 년도;