/*
	DML 실습
*/
-- [1]
SELECT CLASS_TYPE_NO AS "번호", CLASS_TYPE_NAME AS "유형이름" FROM TB_CLASS_TYPE;

INSERT INTO TB_CLASS_TYPE VALUES ('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05', '논문지도');

-- [2]
CREATE TABLE TB_GENERAL_STUDENT_INFO AS (
	SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
	FROM TB_STUDENT
);
SELECT * FROM TB_GENERAL_STUDENT_INFO;

-- [3]
-- 국어국문학과 학생들 조회
--SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')), PROFESSOR_NAME
--	FROM TB_STUDENT
--		JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
--		JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
--	WHERE DEPARTMENT_NAME = '국어국문학과';

CREATE TABLE TB_DEPARTMENT_KLL AS (
	SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')) AS "BIRTHYEAR", PROFESSOR_NAME
	FROM TB_STUDENT
		JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
		JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
);
-- ORA-00998: 이 식은 열의 별명과 함께 지정해야 합니다
-- EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')) ☞ 제대로 된 컬럼명이 아니므로 별칭을 사용해야 한다!

-- [4]
-- 현 학과들의 정원 조회
--SELECT DEPARTMENT_NO, DEPARTMENT_NAME, CAPACITY
--FROM TB_DEPARTMENT;

-- 10% 증가한 정원 조회
--SELECT ROUND(CAPACITY * 1.1) AS "CAPACITY"
--FROM TB_DEPARTMENT;

-- 적용
UPDATE TB_DEPARTMENT SET CAPACITY = ROUND(CAPACITY * 1.1);

-- [5]
-- 기존 A413042 학번의 학생 정보
SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A413042';

UPDATE TB_STUDENT
	SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

ROLLBACK;

-- [6]
-- 기존 주민번호 데이터 조회
SELECT STUDENT_SSN
FROM TB_STUDENT;

UPDATE TB_STUDENT
	SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);
	
ROLLBACK;

-- [7] 
-- 잘못되었다는 의학과 김명훈 학생의 2005년 1학기 피부생리학 점수 조회
--SELECT STUDENT_NAME, DEPARTMENT_NAME, TERM_NO, POINT
--FROM TB_STUDENT
--	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
--	JOIN TB_GRADE USING (STUDENT_NO)
--	JOIN TB_CLASS USING (CLASS_NO)
--WHERE STUDENT_NAME = '김명훈'	 AND DEPARTMENT_NAME = '의학과' AND TERM_NO = '200501' AND CLASS_NAME = '피부생리학';

UPDATE TB_GRADE
	SET POINT = 3.5
WHERE (TERM_NO, STUDENT_NO, POINT) = (
	SELECT TERM_NO, STUDENT_NO, POINT
	FROM TB_STUDENT
		JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
		JOIN TB_GRADE USING (STUDENT_NO)
		JOIN TB_CLASS USING (CLASS_NO)
	WHERE STUDENT_NAME = '김명훈'	 AND DEPARTMENT_NAME = '의학과' AND TERM_NO = '200501' AND CLASS_NAME = '피부생리학'
);
-- ROLLBACK;
-- [8]
-- 휴학생 조회
SELECT STUDENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

-- 기존 데이터
SELECT *
FROM TB_GRADE;

DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (
	SELECT STUDENT_NO
	FROM TB_STUDENT
	WHERE ABSENCE_YN = 'Y'
);
-- ROLLBACK;