-- MEMBER TABLE
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
	MEM_NO NUMBER PRIMARY KEY,
	MEM_ID VARCHAR2(20) UNIQUE,
	MEM_PW VARCHAR2(20)
);
DROP SEQUENCE SEQ_MEM_NO;
CREATE SEQUENCE SEQ_MEM_NO NOCYCLE NOCACHE;

INSERT INTO MEMBER VALUES (SEQ_MEM_NO.NEXTVAL, 'ADMIN', '1234');

-- DEVELOPER 테이블
DROP TABLE DEVELOPER;
CREATE TABLE DEVELOPER (
	DEV_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR(20) CONSTRAINT FK_MEMBER_ID REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE UNIQUE,
    DEV_NAME VARCHAR2(100) NOT NULL,
    DEV_JOB VARCHAR2(50) NOT NULL,
    DEV_HP NUMBER DEFAULT 100,
    DEV_LEVEL NUMBER DEFAULT 1,
    DEV_EXP NUMBER DEFAULT 0,
    DEV_TURN NUMBER DEFAULT 1
);

DROP SEQUENCE SEQ_DEV_NO;
CREATE SEQUENCE SEQ_DEV_NO NOCYCLE NOCACHE;
INSERT INTO DEVELOPER VALUES (SEQ_DEV_NO.NEXTVAL, 'ADMIN', 'jun', '프론트엔드 개발자', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
DELETE FROM DEVELOPER;

-- SKILL 테이블
DROP TABLE SKILL;
CREATE TABLE SKILL (
    SKILL_NO NUMBER PRIMARY KEY,
    DEVELOPER_NO NUMBER NOT NULL,
    SKILL_NAME VARCHAR2(100) NOT NULL,
    SKILL_EXP NUMBER DEFAULT 0,
    SKILL_LEVEL NUMBER DEFAULT 1,
    CONSTRAINT FK_DEVELOPER_NO FOREIGN KEY (DEVELOPER_NO) REFERENCES DEVELOPER (DEV_NO) ON DELETE CASCADE
);

DROP SEQUENCE SEQ_SKILL_NO;
CREATE SEQUENCE SEQ_SKILL_NO NOCYCLE NOCACHE;

-- Question 테이블
DROP TABLE QUESTION;
CREATE TABLE QUESTION (
    QUESTION_NO NUMBER PRIMARY KEY,
    QUESTION_TEXT VARCHAR2(500) NOT NULL,
    QUESTION_HINT VARCHAR2(500),
    QUESTION_ANSWER NUMBER NOT NULL
);

DROP SEQUENCE SEQ_QUESTION_NO;
CREATE SEQUENCE SEQ_QUESTION_NO NOCYCLE NOCACHE;








select * from developer;