/*
	SQL03_SELECT(Option)
*/
-- [1]
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1;

-- [2]
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SYSDATE - TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD');

-- [3]
SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
ORDER BY STUDENT_NAME;

-- [4]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '법학과')
ORDER BY SYSDATE - TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD') DESC;

-- [5]
SELECT STUDENT_NO, TO_CHAR(POINT, '9.99') AS "POINT"
FROM TB_STUDENT
	JOIN TB_GRADE USING (STUDENT_NO)
WHERE (TERM_NO IN (
	SELECT TERM_NO
	FROM TB_GRADE
	WHERE TERM_NO = '200402'
)) AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO;

-- [6]
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
	JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

-- [7]
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY DEPARTMENT_NO;

-- [8]
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS TC
	JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
	JOIN TB_PROFESSOR USING (PROFESSOR_NO)
	JOIN TB_DEPARTMENT TD ON (TC.DEPARTMENT_NO = TD.DEPARTMENT_NO)
ORDER BY TC.DEPARTMENT_NO, PROFESSOR_NAME, CLASS_NAME;

-- [9]
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS TC
	JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
	JOIN TB_PROFESSOR USING (PROFESSOR_NO)
	JOIN TB_DEPARTMENT TD ON (TC.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY TC.DEPARTMENT_NO, PROFESSOR_NAME, CLASS_NAME;

-- [10]
--SELECT STUDENT_NO, STUDENT_NAME
--FROM TB_STUDENT
--	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
--WHERE DEPARTMENT_NAME = '음악학과'
--ORDER BY STUDENT_NO;

SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT), 1) AS "전체 평점"
FROM
	TB_GRADE
	JOIN  (
		SELECT STUDENT_NO, STUDENT_NAME
		FROM TB_STUDENT
			JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
		WHERE DEPARTMENT_NAME = '음악학과'
	) USING (STUDENT_NO)
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;

-- [11]
--SELECT COACH_PROFESSOR_NO, DEPARTMENT_NAME
--FROM TB_STUDENT
--	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
--WHERE STUDENT_NO = 'A313047';
--
--SELECT DEPARTMENT_NAME
--FROM TB_DEPARTMENT
--WHERE DEPARTMENT_NO = (
--	SELECT DEPARTMENT_NO
--	FROM TB_STUDENT
--	WHERE STUDENT_NO = 'A313047'
--);
--
--SELECT PROFESSOR_NAME AS "지도교수"
--FROM TB_PROFESSOR
--WHERE PROFESSOR_NO = (
--	SELECT COACH_PROFESSOR_NO
--	FROM TB_STUDENT
--	WHERE STUDENT_NO = 'A313047'
--);

SELECT DEPARTMENT_NAME AS "학과이름", STUDENT_NAME AS "학생이름", PROFESSOR_NAME AS "지도교수"
FROM TB_STUDENT
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE STUDENT_NO = 'A313047';

-- [12]
SELECT STUDENT_NAME, TERM_NO AS "TERM_NAME"
FROM TB_STUDENT
	JOIN TB_GRADE USING (STUDENT_NO)
	JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론';

-- [13]
-- 미해결
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IN (
	SELECT PROFESSOR_NO
	FROM TB_PROFESSOR
);







